# -*- coding: utf-8 -*-\n
{'name': 'Employee Salary Report', 
 'version': '19.0.0', 
 'summary': 'Generate salary reports automatically from payslips (CTC, Gross, Deductions, CTC breakdown)', 
 'description': 'Creates employee.salary.report records when payslips are validated. Includes computed fields for Basic+DA, HRA, PF, ESI, CTC and more. Default list grouped by month.', 
 'author': 'Generated by ChatGPT for user', 
 'category': 'Human Resources/Payroll', 
 'depends': ['hr', 'hr_payroll'], 
 'data': [
    'security/ir.model.access.csv', 
     # 'views/employee_salary_report_views.xml',
      # 'views/hr_version_view_inherit.xml'
 ]
'installable': True, 
'application': False, 
'license': 'LGPL-3'}
